name: food_delivery_app_ui
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts:
  build_runner: ">=2.3.3"
  introduction_screen:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
flutter_gen:
  integrations:
    lottie: true
  fonts:
    enabled: false
  colors:
    enabled: false
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
      package_parameter_enabled: true
    exclude:
      - assets/**/2x/**
      - assets/**/3x/**
